language : python
dist: bionic

sudo: required

addons:
    chrome: stable

services:
  - docker

python:
  - "2.7"
  - "3.6"

matrix:
  fast_finish: true

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install pep8 node
  - git clone https://github.com/Statoil/webviz.git

install:
  - pip install -r requirements.txt
  - pip install -r dev-requirements.txt
  - cd ./webviz
  - make build && make install
  - cd ..
  - wget https://chromedriver.storage.googleapis.com/2.42/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip
  - export PATH=$PATH:$PWD

script:
  - make build
  - make lint
  - make dev-install
  - make test
  - #make doc
  - make install
