language : python
cache: pip

sudo: true

addons:
    chrome: stable


services:
  - docker

python:
  - "2.7"
  - "3.6"

matrix:
  fast_finish: true

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install pep8 node
language : python
cache: pip

sudo: true

addons:
    chrome: stable


services:
  - docker

python:
  - "2.7"
  - "3.6"

matrix:
  fast_finish: true

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install pep8 node
  - pushd ..
  - export ROOT="$PWD"
  - git clone https://github.com/Statoil/webviz.git
  - popd

install:
  - pip install -r requirements.txt
  - pip install -r dev-requirements.txt
  - pushd $ROOT/webviz
  - make build && make install
  - popd
  - wget https://chromedriver.storage.googleapis.com/2.40/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip
  - export PATH=$PATH:$PWD

script:
  - make build
  - make lint
  - make dev-install
  - make test
  - make doc
  - make install


install:
  - pip install -r requirements.txt
  - pip install -r dev-requirements.txt
  - wget https://chromedriver.storage.googleapis.com/2.40/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip
  - export PATH=$PATH:$PWD

script:
  - make build
  - make lint
  - make dev-install
  - make test
  - make doc
  - make install

